import type { SourceDefinition } from "./contracts";

export const sourceCatalog: readonly SourceDefinition[] = [
  {
    code: "DATA_CALENDAR",
    name: "Calendário oficial",
    domain: "shared",
    operation: null,
    entityName: "00 - DATA",
    expectedGrain: "uma data por linha",
    frequency: "daily",
    owner: null,
    sensitivity: "internal",
    status: "pending_connection",
    driveId: null,
    path: null,
    tableOrSheet: null,
    lastSuccessfulRunAt: null,
  },
  {
    code: "BASE_DATASYS",
    name: "Base Datasys",
    domain: "commercial",
    operation: "TIM",
    entityName: "BASE DATASYS",
    expectedGrain: "uma ativação ou mudança de status por linha",
    frequency: "intraday",
    owner: null,
    sensitivity: "restricted",
    status: "pending_connection",
    driveId: null,
    path: null,
    tableOrSheet: null,
    lastSuccessfulRunAt: null,
  },
  {
    code: "BASE_SALES",
    name: "Base de vendas",
    domain: "commercial",
    operation: "TIM",
    entityName: "BASE VENDAS",
    expectedGrain: "um pedido ou item vendido por linha",
    frequency: "intraday",
    owner: null,
    sensitivity: "restricted",
    status: "pending_connection",
    driveId: null,
    path: null,
    tableOrSheet: null,
    lastSuccessfulRunAt: null,
  },
  {
    code: "BASE_CUSTOMIZATION",
    name: "Base CUST",
    domain: "commercial",
    operation: "TIM",
    entityName: "BASE CUST",
    expectedGrain: "a confirmar na etapa de linhagem",
    frequency: "daily",
    owner: null,
    sensitivity: "internal",
    status: "pending_connection",
    driveId: null,
    path: null,
    tableOrSheet: null,
    lastSuccessfulRunAt: null,
  },
  {
    code: "STORE_UNIFIED_AUX",
    name: "Auxiliar unificada para lojas",
    domain: "shared",
    operation: "TIM",
    entityName: "AUXILIAR UNIFICADA PARA LOJAS",
    expectedGrain: "uma loja e vigência organizacional por linha",
    frequency: "daily",
    owner: null,
    sensitivity: "internal",
    status: "pending_connection",
    driveId: null,
    path: null,
    tableOrSheet: null,
    lastSuccessfulRunAt: null,
  },
  {
    code: "PBI_METRICS_RT",
    name: "Medidas Realizado e Tendência",
    domain: "semantic",
    operation: "TIM",
    entityName: "Medidas Realizado e Tendência",
    expectedGrain: "tabela de medidas sem linhas analíticas",
    frequency: "on_demand",
    owner: null,
    sensitivity: "internal",
    status: "pending_connection",
    driveId: null,
    path: null,
    tableOrSheet: null,
    lastSuccessfulRunAt: null,
  },
] as const;

export function getSourceDefinition(code: string): SourceDefinition | undefined {
  return sourceCatalog.find((source) => source.code === code);
}
